import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavWebLogged from "./components/NavWebLogged";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row w-screen h-full">
          <NavWebLogged selectedElement={"Dashboard"} />

          <div className="bg-gray-100 w-full h-full">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
